// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "req_agent_odb.hpp"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/oracle/traits.hxx>
#include <odb/oracle/database.hxx>
#include <odb/oracle/transaction.hxx>
#include <odb/oracle/connection.hxx>
#include <odb/oracle/statement.hxx>
#include <odb/oracle/statement-cache.hxx>
#include <odb/oracle/no-id-object-statements.hxx>
#include <odb/oracle/view-statements.hxx>
#include <odb/oracle/container-statements.hxx>
#include <odb/oracle/exceptions.hxx>
#include <odb/oracle/no-id-object-result.hxx>
#include <odb/oracle/view-result.hxx>

namespace odb
{
  // ns2__reg_agent_obj
  //

  void access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::
  bind (oracle::bind* b,
        image_type& i,
        oracle::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace oracle;

    std::size_t n (0);

    // tx_id
    //
    b[n].type = oracle::bind::number;
    b[n].buffer = i.tx_id_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.tx_id_value));
    b[n].size = &i.tx_id_size;
    b[n].indicator = &i.tx_id_indicator;
    n++;

    // tx_type
    //
    b[n].type = oracle::bind::uinteger;
    b[n].buffer = &i.tx_type_value;
    b[n].capacity = 4;
    b[n].size = 0;
    b[n].indicator = &i.tx_type_indicator;
    n++;

    // hypertag_id
    //
    b[n].type = oracle::bind::number;
    b[n].buffer = i.hypertag_id_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.hypertag_id_value));
    b[n].size = &i.hypertag_id_size;
    b[n].indicator = &i.hypertag_id_indicator;
    n++;

    // bank_code
    //
    b[n].type = oracle::bind::uinteger;
    b[n].buffer = &i.bank_code_value;
    b[n].capacity = 4;
    b[n].size = 0;
    b[n].indicator = &i.bank_code_indicator;
    n++;

    // agent_code
    //
    b[n].type = oracle::bind::string;
    b[n].buffer = i.agent_code_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.agent_code_value));
    b[n].size = &i.agent_code_size;
    b[n].indicator = &i.agent_code_indicator;
    n++;

    // cif_id
    //
    b[n].type = oracle::bind::number;
    b[n].buffer = i.cif_id_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.cif_id_value));
    b[n].size = &i.cif_id_size;
    b[n].indicator = &i.cif_id_indicator;
    n++;

    // acc_id
    //
    b[n].type = oracle::bind::string;
    b[n].buffer = i.acc_id_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.acc_id_value));
    b[n].size = &i.acc_id_size;
    b[n].indicator = &i.acc_id_indicator;
    n++;

    // acc_type
    //
    b[n].type = oracle::bind::uinteger;
    b[n].buffer = &i.acc_type_value;
    b[n].capacity = 4;
    b[n].size = 0;
    b[n].indicator = &i.acc_type_indicator;
    n++;

    // net_operator
    //
    b[n].type = oracle::bind::string;
    b[n].buffer = i.net_operator_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.net_operator_value));
    b[n].size = &i.net_operator_size;
    b[n].indicator = &i.net_operator_indicator;
    n++;
  }

  void access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::
  init (image_type& i,
        const object_type& o,
        oracle::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace oracle;

    if (i.change_callback_.callback != 0)
      (i.change_callback_.callback) (i.change_callback_.context);

    // tx_id
    //
    {
      ::uint64_t const& v =
        o.tx_id;

      bool is_null (false);
      std::size_t size (0);
      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_image (
        i.tx_id_value,
        size,
        is_null,
        v);
      i.tx_id_indicator = is_null ? -1 : 0;
      i.tx_id_size = static_cast<ub2> (size);
    }

    // tx_type
    //
    {
      ::uint16_t const& v =
        o.tx_type;

      bool is_null (false);
      oracle::value_traits<
          ::uint16_t,
          oracle::id_int32 >::set_image (
        i.tx_type_value, is_null, v);
      i.tx_type_indicator = is_null ? -1 : 0;
    }

    // hypertag_id
    //
    {
      ::uint64_t const& v =
        o.hypertag_id;

      bool is_null (false);
      std::size_t size (0);
      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_image (
        i.hypertag_id_value,
        size,
        is_null,
        v);
      i.hypertag_id_indicator = is_null ? -1 : 0;
      i.hypertag_id_size = static_cast<ub2> (size);
    }

    // bank_code
    //
    {
      ::uint32_t const& v =
        o.bank_code;

      bool is_null (false);
      oracle::value_traits<
          ::uint32_t,
          oracle::id_int32 >::set_image (
        i.bank_code_value, is_null, v);
      i.bank_code_indicator = is_null ? -1 : 0;
    }

    // agent_code
    //
    {
      ::std::string const& v =
        o.agent_code;

      bool is_null (true);
      std::size_t size (0);
      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_image (
        i.agent_code_value,
        sizeof (i.agent_code_value),
        size,
        is_null,
        v);
      i.agent_code_indicator = is_null ? -1 : 0;
      i.agent_code_size = static_cast<ub2> (size);
    }

    // cif_id
    //
    {
      ::uint64_t const& v =
        o.cif_id;

      bool is_null (false);
      std::size_t size (0);
      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_image (
        i.cif_id_value,
        size,
        is_null,
        v);
      i.cif_id_indicator = is_null ? -1 : 0;
      i.cif_id_size = static_cast<ub2> (size);
    }

    // acc_id
    //
    {
      ::std::string const& v =
        o.acc_id;

      bool is_null (true);
      std::size_t size (0);
      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_image (
        i.acc_id_value,
        sizeof (i.acc_id_value),
        size,
        is_null,
        v);
      i.acc_id_indicator = is_null ? -1 : 0;
      i.acc_id_size = static_cast<ub2> (size);
    }

    // acc_type
    //
    {
      ::uint8_t const& v =
        o.acc_type;

      bool is_null (false);
      oracle::value_traits<
          ::uint8_t,
          oracle::id_int32 >::set_image (
        i.acc_type_value, is_null, v);
      i.acc_type_indicator = is_null ? -1 : 0;
    }

    // net_operator
    //
    {
      ::std::string const& v =
        o.net_operator;

      bool is_null (true);
      std::size_t size (0);
      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_image (
        i.net_operator_value,
        sizeof (i.net_operator_value),
        size,
        is_null,
        v);
      i.net_operator_indicator = is_null ? -1 : 0;
      i.net_operator_size = static_cast<ub2> (size);
    }
  }

  void access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // tx_id
    //
    {
      ::uint64_t& v =
        o.tx_id;

      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_value (
        v,
        i.tx_id_value,
        i.tx_id_size,
        i.tx_id_indicator == -1);
    }

    // tx_type
    //
    {
      ::uint16_t& v =
        o.tx_type;

      oracle::value_traits<
          ::uint16_t,
          oracle::id_int32 >::set_value (
        v,
        i.tx_type_value,
        i.tx_type_indicator == -1);
    }

    // hypertag_id
    //
    {
      ::uint64_t& v =
        o.hypertag_id;

      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_value (
        v,
        i.hypertag_id_value,
        i.hypertag_id_size,
        i.hypertag_id_indicator == -1);
    }

    // bank_code
    //
    {
      ::uint32_t& v =
        o.bank_code;

      oracle::value_traits<
          ::uint32_t,
          oracle::id_int32 >::set_value (
        v,
        i.bank_code_value,
        i.bank_code_indicator == -1);
    }

    // agent_code
    //
    {
      ::std::string& v =
        o.agent_code;

      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_value (
        v,
        i.agent_code_value,
        i.agent_code_size,
        i.agent_code_indicator == -1);
    }

    // cif_id
    //
    {
      ::uint64_t& v =
        o.cif_id;

      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_value (
        v,
        i.cif_id_value,
        i.cif_id_size,
        i.cif_id_indicator == -1);
    }

    // acc_id
    //
    {
      ::std::string& v =
        o.acc_id;

      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_value (
        v,
        i.acc_id_value,
        i.acc_id_size,
        i.acc_id_indicator == -1);
    }

    // acc_type
    //
    {
      ::uint8_t& v =
        o.acc_type;

      oracle::value_traits<
          ::uint8_t,
          oracle::id_int32 >::set_value (
        v,
        i.acc_type_value,
        i.acc_type_indicator == -1);
    }

    // net_operator
    //
    {
      ::std::string& v =
        o.net_operator;

      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_value (
        v,
        i.net_operator_value,
        i.net_operator_size,
        i.net_operator_indicator == -1);
    }
  }

  const char access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::persist_statement[] =
  "INSERT INTO \"ns2__reg_agent_obj\" "
  "(\"tx_id\", "
  "\"tx_type\", "
  "\"hypertag_id\", "
  "\"bank_code\", "
  "\"agent_code\", "
  "\"cif_id\", "
  "\"acc_id\", "
  "\"acc_type\", "
  "\"net_operator\") "
  "VALUES "
  "(:1, :2, :3, :4, :5, :6, :7, :8, :9)";

  const char access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::query_statement[] =
  "SELECT "
  "\"ns2__reg_agent_obj\".\"tx_id\", "
  "\"ns2__reg_agent_obj\".\"tx_type\", "
  "\"ns2__reg_agent_obj\".\"hypertag_id\", "
  "\"ns2__reg_agent_obj\".\"bank_code\", "
  "\"ns2__reg_agent_obj\".\"agent_code\", "
  "\"ns2__reg_agent_obj\".\"cif_id\", "
  "\"ns2__reg_agent_obj\".\"acc_id\", "
  "\"ns2__reg_agent_obj\".\"acc_type\", "
  "\"ns2__reg_agent_obj\".\"net_operator\" "
  "FROM \"ns2__reg_agent_obj\"";

  const char access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::erase_query_statement[] =
  "DELETE FROM \"ns2__reg_agent_obj\"";

  const char access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::table_name[] =
  "\"ns2__reg_agent_obj\"";

  void access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    init (im, obj, statement_insert);

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  result< access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::object_type >
  access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::
  query (database&, const query_base_type& q)
  {
    using namespace oracle;
    using odb::details::shared;
    using odb::details::shared_ptr;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::no_id_object_result_impl<object_type> > r (
      new (shared) oracle::no_id_object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::ns2__reg_agent_obj, id_oracle >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // ns2__reg_customer_obj
  //

  void access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::
  bind (oracle::bind* b,
        image_type& i,
        oracle::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace oracle;

    std::size_t n (0);

    // tx_id
    //
    b[n].type = oracle::bind::number;
    b[n].buffer = i.tx_id_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.tx_id_value));
    b[n].size = &i.tx_id_size;
    b[n].indicator = &i.tx_id_indicator;
    n++;

    // tx_type
    //
    b[n].type = oracle::bind::uinteger;
    b[n].buffer = &i.tx_type_value;
    b[n].capacity = 4;
    b[n].size = 0;
    b[n].indicator = &i.tx_type_indicator;
    n++;

    // hypertag_id
    //
    b[n].type = oracle::bind::number;
    b[n].buffer = i.hypertag_id_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.hypertag_id_value));
    b[n].size = &i.hypertag_id_size;
    b[n].indicator = &i.hypertag_id_indicator;
    n++;

    // signup_date
    //
    b[n].type = oracle::bind::string;
    b[n].buffer = i.signup_date_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.signup_date_value));
    b[n].size = &i.signup_date_size;
    b[n].indicator = &i.signup_date_indicator;
    n++;

    // agent_code
    //
    b[n].type = oracle::bind::string;
    b[n].buffer = i.agent_code_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.agent_code_value));
    b[n].size = &i.agent_code_size;
    b[n].indicator = &i.agent_code_indicator;
    n++;

    // initial_deposit
    //
    b[n].type = oracle::bind::number;
    b[n].buffer = i.initial_deposit_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.initial_deposit_value));
    b[n].size = &i.initial_deposit_size;
    b[n].indicator = &i.initial_deposit_indicator;
    n++;
  }

  void access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::
  init (image_type& i,
        const object_type& o,
        oracle::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace oracle;

    if (i.change_callback_.callback != 0)
      (i.change_callback_.callback) (i.change_callback_.context);

    // tx_id
    //
    {
      ::uint64_t const& v =
        o.tx_id;

      bool is_null (false);
      std::size_t size (0);
      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_image (
        i.tx_id_value,
        size,
        is_null,
        v);
      i.tx_id_indicator = is_null ? -1 : 0;
      i.tx_id_size = static_cast<ub2> (size);
    }

    // tx_type
    //
    {
      ::uint16_t const& v =
        o.tx_type;

      bool is_null (false);
      oracle::value_traits<
          ::uint16_t,
          oracle::id_int32 >::set_image (
        i.tx_type_value, is_null, v);
      i.tx_type_indicator = is_null ? -1 : 0;
    }

    // hypertag_id
    //
    {
      ::uint64_t const& v =
        o.hypertag_id;

      bool is_null (false);
      std::size_t size (0);
      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_image (
        i.hypertag_id_value,
        size,
        is_null,
        v);
      i.hypertag_id_indicator = is_null ? -1 : 0;
      i.hypertag_id_size = static_cast<ub2> (size);
    }

    // signup_date
    //
    {
      ::std::string const& v =
        o.signup_date;

      bool is_null (true);
      std::size_t size (0);
      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_image (
        i.signup_date_value,
        sizeof (i.signup_date_value),
        size,
        is_null,
        v);
      i.signup_date_indicator = is_null ? -1 : 0;
      i.signup_date_size = static_cast<ub2> (size);
    }

    // agent_code
    //
    {
      ::std::string const& v =
        o.agent_code;

      bool is_null (true);
      std::size_t size (0);
      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_image (
        i.agent_code_value,
        sizeof (i.agent_code_value),
        size,
        is_null,
        v);
      i.agent_code_indicator = is_null ? -1 : 0;
      i.agent_code_size = static_cast<ub2> (size);
    }

    // initial_deposit
    //
    {
      ::uint64_t const& v =
        o.initial_deposit;

      bool is_null (false);
      std::size_t size (0);
      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_image (
        i.initial_deposit_value,
        size,
        is_null,
        v);
      i.initial_deposit_indicator = is_null ? -1 : 0;
      i.initial_deposit_size = static_cast<ub2> (size);
    }
  }

  void access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // tx_id
    //
    {
      ::uint64_t& v =
        o.tx_id;

      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_value (
        v,
        i.tx_id_value,
        i.tx_id_size,
        i.tx_id_indicator == -1);
    }

    // tx_type
    //
    {
      ::uint16_t& v =
        o.tx_type;

      oracle::value_traits<
          ::uint16_t,
          oracle::id_int32 >::set_value (
        v,
        i.tx_type_value,
        i.tx_type_indicator == -1);
    }

    // hypertag_id
    //
    {
      ::uint64_t& v =
        o.hypertag_id;

      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_value (
        v,
        i.hypertag_id_value,
        i.hypertag_id_size,
        i.hypertag_id_indicator == -1);
    }

    // signup_date
    //
    {
      ::std::string& v =
        o.signup_date;

      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_value (
        v,
        i.signup_date_value,
        i.signup_date_size,
        i.signup_date_indicator == -1);
    }

    // agent_code
    //
    {
      ::std::string& v =
        o.agent_code;

      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_value (
        v,
        i.agent_code_value,
        i.agent_code_size,
        i.agent_code_indicator == -1);
    }

    // initial_deposit
    //
    {
      ::uint64_t& v =
        o.initial_deposit;

      oracle::value_traits<
          ::uint64_t,
          oracle::id_big_int >::set_value (
        v,
        i.initial_deposit_value,
        i.initial_deposit_size,
        i.initial_deposit_indicator == -1);
    }
  }

  const char access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::persist_statement[] =
  "INSERT INTO \"ns2__reg_customer_obj\" "
  "(\"tx_id\", "
  "\"tx_type\", "
  "\"hypertag_id\", "
  "\"signup_date\", "
  "\"agent_code\", "
  "\"initial_deposit\") "
  "VALUES "
  "(:1, :2, :3, :4, :5, :6)";

  const char access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::query_statement[] =
  "SELECT "
  "\"ns2__reg_customer_obj\".\"tx_id\", "
  "\"ns2__reg_customer_obj\".\"tx_type\", "
  "\"ns2__reg_customer_obj\".\"hypertag_id\", "
  "\"ns2__reg_customer_obj\".\"signup_date\", "
  "\"ns2__reg_customer_obj\".\"agent_code\", "
  "\"ns2__reg_customer_obj\".\"initial_deposit\" "
  "FROM \"ns2__reg_customer_obj\"";

  const char access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::erase_query_statement[] =
  "DELETE FROM \"ns2__reg_customer_obj\"";

  const char access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::table_name[] =
  "\"ns2__reg_customer_obj\"";

  void access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    init (im, obj, statement_insert);

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  result< access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::object_type >
  access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::
  query (database&, const query_base_type& q)
  {
    using namespace oracle;
    using odb::details::shared;
    using odb::details::shared_ptr;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::no_id_object_result_impl<object_type> > r (
      new (shared) oracle::no_id_object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::ns2__reg_customer_obj, id_oracle >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // count_reg_agent
  //

  void access::view_traits_impl< ::count_reg_agent, id_oracle >::
  bind (oracle::bind* b,
        image_type& i)
  {
    using namespace oracle;

    oracle::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // cnt
    //
    b[n].type = oracle::bind::binary_double;
    b[n].buffer= &i.cnt_value;
    b[n].capacity = 8;
    b[n].size = 0;
    b[n].indicator = &i.cnt_indicator;
    n++;
  }

  void access::view_traits_impl< ::count_reg_agent, id_oracle >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // cnt
    //
    {
      int& v =
        o.cnt;

      oracle::value_traits<
          int,
          oracle::id_double >::set_value (
        v,
        i.cnt_value,
        i.cnt_indicator == -1);
    }
  }

  access::view_traits_impl< ::count_reg_agent, id_oracle >::query_base_type
  access::view_traits_impl< ::count_reg_agent, id_oracle >::
  query_statement (const query_base_type& q)
  {
    query_base_type r (
      "SELECT "
      "count(*) ");

    r += "FROM \"ns2__reg_agent_obj\"";

    if (!q.empty ())
    {
      r += " ";
      r += q.clause_prefix ();
      r += q;
    }

    return r;
  }

  result< access::view_traits_impl< ::count_reg_agent, id_oracle >::view_type >
  access::view_traits_impl< ::count_reg_agent, id_oracle >::
  query (database&, const query_base_type& q)
  {
    using namespace oracle;
    using odb::details::shared;
    using odb::details::shared_ptr;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (query_statement (q));
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        qs.clause (),
        false,
        true,
        qs.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) oracle::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }
}

#include <odb/post.hxx>
