/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

SET FEEDBACK OFF;
WHENEVER SQLERROR EXIT FAILURE;
WHENEVER OSERROR EXIT FAILURE;

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "ns2__reg_customer_obj" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "ns2__reg_agent_obj" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;
END;
/

CREATE TABLE "ns2__reg_agent_obj" (
  "tx_id" NUMBER(20) NOT NULL,
  "tx_type" NUMBER(5) NOT NULL,
  "hypertag_id" NUMBER(20) NOT NULL,
  "bank_code" NUMBER(10) NOT NULL,
  "agent_code" VARCHAR2(512) NULL,
  "cif_id" NUMBER(20) NOT NULL,
  "acc_id" VARCHAR2(512) NULL,
  "acc_type" NUMBER(3) NOT NULL,
  "net_operator" VARCHAR2(512) NULL);

CREATE TABLE "ns2__reg_customer_obj" (
  "tx_id" NUMBER(20) NOT NULL,
  "tx_type" NUMBER(5) NOT NULL,
  "hypertag_id" NUMBER(20) NOT NULL,
  "signup_date" VARCHAR2(512) NULL,
  "agent_code" VARCHAR2(512) NULL,
  "initial_deposit" NUMBER(20) NOT NULL);

EXIT;
