// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb
{
  // ns2__reg_agent_obj
  //

  inline
  access::object_traits< ::ns2__reg_agent_obj >::id_type
  access::object_traits< ::ns2__reg_agent_obj >::
  id (const object_type&)
  {
  }

  inline
  void access::object_traits< ::ns2__reg_agent_obj >::
  callback (database& db, object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  inline
  void access::object_traits< ::ns2__reg_agent_obj >::
  callback (database& db, const object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  // ns2__reg_customer_obj
  //

  inline
  access::object_traits< ::ns2__reg_customer_obj >::id_type
  access::object_traits< ::ns2__reg_customer_obj >::
  id (const object_type&)
  {
  }

  inline
  void access::object_traits< ::ns2__reg_customer_obj >::
  callback (database& db, object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  inline
  void access::object_traits< ::ns2__reg_customer_obj >::
  callback (database& db, const object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }
}

namespace odb
{
  // ns2__reg_agent_obj
  //

  // ns2__reg_customer_obj
  //
}

