// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef STUDENT_ODB_HPP
#define STUDENT_ODB_HPP

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "student.hpp"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // student
  //
  template <>
  struct class_traits< ::student >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::student >
  {
    public:
    typedef ::student object_type;
    typedef ::student* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/oracle/version.hxx>
#include <odb/oracle/forward.hxx>
#include <odb/oracle/binding.hxx>
#include <odb/oracle/oracle-types.hxx>
#include <odb/oracle/query.hxx>

namespace odb
{
  // student
  //
  template <typename A>
  struct query_columns< ::student, id_oracle, A >
  {
    // id
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        int,
        oracle::id_int32 >::query_type,
      oracle::id_int32 >
    id_type_;

    static const id_type_ id;

    // name
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::std::string,
        oracle::id_string >::query_type,
      oracle::id_string >
    name_type_;

    static const name_type_ name;
  };

  template <typename A>
  const typename query_columns< ::student, id_oracle, A >::id_type_
  query_columns< ::student, id_oracle, A >::
  id (A::table_name, "\"ID\"", 0, 10);

  template <typename A>
  const typename query_columns< ::student, id_oracle, A >::name_type_
  query_columns< ::student, id_oracle, A >::
  name (A::table_name, "\"NAME\"", 0, 512);

  template <typename A>
  struct pointer_query_columns< ::student, id_oracle, A >:
    query_columns< ::student, id_oracle, A >
  {
  };

  template <>
  class access::object_traits_impl< ::student, id_oracle >:
    public access::object_traits< ::student >
  {
    public:
    static const std::size_t batch = 1UL;

    struct id_image_type
    {
      int id_value;
      sb2 id_indicator;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      int id_value;
      sb2 id_indicator;

      // name
      //
      char name_value[512];
      ub2 name_size;
      sb2 name_indicator;

      std::size_t version;

      oracle::change_callback change_callback_;

      oracle::change_callback*
      change_callback ()
      {
        return &change_callback_;
      }
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static void
    bind (oracle::bind*,
          image_type&,
          oracle::statement_kind);

    static void
    bind (oracle::bind*, id_image_type&);

    static void
    init (image_type&,
          const object_type&,
          oracle::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef oracle::object_statements<object_type> statements_type;

    typedef oracle::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::student, id_common >:
    public access::object_traits_impl< ::student, id_oracle >
  {
  };

  // student
  //
}

#include "student-odb_inline.hpp"

#include <odb/post.hxx>

#endif // STUDENT_ODB_HPP
